######BachDangTuan#######
##Docker-compose ELK-stack duoc viet boi Bach Dang Tuan##
version: '3.3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elastic/elasticsearch.yml
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    container_name: kibana
    volumes:
      - ./kibana/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  esdata1:
    driver: local