######BachDangTuan#######
##Docker-compose ELK-stack duoc viet boi Bach Dang Tuan##
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3  # images moi nhat cua ELK stack
    ports:
      - 9200:9200                                               
    volumes:
      - .elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    depends_on:
      - elasticsearch  
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - 5601:5601
    volumes:
      - .kibana/kibana.yml:/usr/share/kibana/config/kibana.yml