######BachDangTuan#######
##Docker-compose ELK-stack duoc viet boi Bach Dang Tuan##
version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    ports:
      - 9200:9200

  kibana:
    depends_on:
      - elasticsearch  
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - 5601:5601